# Allows using HTTPStatus.OK instead of the magic number 200
from http import HTTPStatus
import pytest

# Import the authentication client and its Pydantic schemas:
# LoginRequestSchema — what we send.
# LoginResponseSchema — what we receive.
from clients.authentication.authentication_client import get_authentication_client,AuthenticationClient
from clients.authentication.authentication_schema import LoginRequestSchema, LoginResponseSchema

# User creation client and request schema.
from clients.users.public_users_client import get_public_users_client,PublicUsersClient
from clients.users.users_schema import CreateUserRequestSchema
from tests.conftest import UserFixture

# Custom (my own) assertion functions.
from tools.assertions.authentication import assert_login_response
from tools.assertions.base import assert_status_code
from tools.assertions.schema import validate_json_schema

# Pytest automatically detects and executes this test.
@pytest.mark.regression
@pytest.mark.authentication
def test_login(function_user:UserFixture,public_users_client: PublicUsersClient, authentication_client:AuthenticationClient):

    request = LoginRequestSchema(email=function_user.email,password=function_user.password)
    response = authentication_client.login_api(request)
    response_data = LoginResponseSchema.model_validate_json(response.text)

    assert_status_code(response.status_code, HTTPStatus.OK)
    assert_login_response(response_data)

    validate_json_schema(response.json(), response_data.model_json_schema())


  # # Old code   1. Initialize clients.
  #   # Objects are created that know where and how to send requests: /users and /authentication/login.
  #   # Two clients are obtained:
  #   #
  #   # public_users_client — POST /api/v1/users
  #   # authentication_client — POST /api/v1/authentication/login
  #   public_users_client = get_public_users_client()
  #   authentication_client = get_authentication_client()
  #
  #   # 2. Create a new user
  #   #  What happens inside:
  #   #  CreateUserRequestSchema generates:
  #   #   - a random email
  #   #   - a random password
  #   #   - other fields (if any)
  #   create_user_request = CreateUserRequestSchema()
  #   # The client sends a POST request to /users
  #   # with a JSON body automatically generated by the schema.
  #   # Why don’t we perform an assert here?
  #   # Because verifying user creation is handled in a separate test.
  #   public_users_client.create_user(create_user_request)
  #
  #   # 3. Build the authorization request
  #   # Login is performed using the same data that was used to create the user.
  #   login_request = LoginRequestSchema(
  #       email=create_user_request.email,
  #       password=create_user_request.password
  #   )
  #
  #   # 4. Execute POST request to /login
  #   #  What the client does:
  #   # - Serializes login_request into JSON
  #   # - Sends a POST request
  #   # - Returns a Response object (status, text, json)
  #   login_response = authentication_client.login_api(login_request)
  #
  #   # 5. Deserialize JSON into LoginResponseSchema
  #   #   Here Pydantic:
  #   # - Reads JSON as a string
  #   # - Validates the structure
  #   # - Creates a Python object - Now this is not a string dictionary, but an object.
  #   login_response_data = LoginResponseSchema.model_validate_json(login_response.text)
  #
  #   # 6. Verify the status code
  #   # If the status code is not 200 → the test will fail with a clear error message.
  #   assert_status_code(login_response.status_code, HTTPStatus.OK)
  #
  #   # 7. Verify the response body content
  #   # The following is verified:
  #   # - tokenType = "bearer"
  #   # - accessToken is not empty
  #   # - refreshToken is not empty
  #   # If accessToken is "", None, or False — the test will fail.
  #   assert_login_response(login_response_data)
  #
  #   # 8. Validate JSON Schema
  #   # - Keys
  #   # - Field types
  #   # - Required fields
  #   # Ensure that the API response fully conforms to the Pydantic schema.
  #   validate_json_schema(login_response.json(), login_response_data.model_json_schema())
